"""
finrag.hallucination.claim_extractor
-------------------------------------
Decomposes an LLM answer into atomic, individually-verifiable claims.

Design
------
- Split on sentence boundaries.
- Skip boilerplate, citation-only lines, and very short fragments.
- Flag numerical claims (sentences with dollar amounts, percentages, or
  explicit numbers) so the NLI verifier can apply extra scrutiny.

Each Claim carries a sentence_index so results map back to the original answer.
"""
from __future__ import annotations

import re

from finrag.models import Claim

# Patterns that flag a sentence as containing financial figures
_NUMERICAL_PATTERNS = [
    r"\$[\d,]+",            # dollar amount
    r"\d+\.?\d*\s*%",      # percentage
    r"\b\d[\d,]*\.?\d*\s*(?:billion|million|thousand|B|M|K)\b",
    r"\bQ[1-4]\b",          # quarter reference
    r"\bFY\s*\d{2,4}\b",   # fiscal year reference
]
_NUMERICAL_RE = re.compile("|".join(_NUMERICAL_PATTERNS), re.IGNORECASE)

# Patterns that mark a sentence as boilerplate (skip it)
_BOILERPLATE_RE = re.compile(
    r"(?:"
    r"forward-looking statements?"
    r"|not incorporated by reference"
    r"|investor relations website"
    r"|corporate social responsibility"
    r"|cause actual results.*differ materially"
    r")",
    re.IGNORECASE,
)

# Sentence is citation-only if it's just [TICKER-date-nnnn]
_CITATION_ONLY_RE = re.compile(r"^\s*(\[[A-Z0-9_.-]+-\d{4}-\d{2}-\d{2}-\d{4}\]\s*)+$")

_MIN_CLAIM_CHARS = 30


def extract_claims(answer: str) -> list[Claim]:
    """
    Return atomic claims from *answer*, filtering out noise.

    Parameters
    ----------
    answer : str
        Full text generated by the LLM (may contain bracketed citations).

    Returns
    -------
    list[Claim]
        One Claim per verifiable sentence, in order.
    """
    # Strip citations before splitting so they don't skew sentence detection
    clean = re.sub(r"\[[A-Z0-9_.-]+-\d{4}-\d{2}-\d{2}-\d{4}\]", "", answer)
    sentences = _split_sentences(clean)

    claims: list[Claim] = []
    for idx, sentence in enumerate(sentences):
        sentence = sentence.strip()
        if len(sentence) < _MIN_CLAIM_CHARS:
            continue
        if _CITATION_ONLY_RE.match(sentence):
            continue
        if _BOILERPLATE_RE.search(sentence):
            continue
        claims.append(
            Claim(
                text=sentence,
                sentence_index=idx,
                is_numerical=bool(_NUMERICAL_RE.search(sentence)),
            )
        )

    return claims


def _split_sentences(text: str) -> list[str]:
    """
    Naive sentence splitter that handles common financial abbreviations
    (e.g. "vs.", "Inc.", "Corp.") without false splits.
    """
    # Protect known abbreviations from being treated as sentence ends
    protected = re.sub(
        r"\b(vs|Inc|Corp|Ltd|Co|Mr|Mrs|Dr|et al|e\.g|i\.e|approx|Fig|Sec|Dept)\.",
        r"\1<DOT>",
        text,
    )
    parts = re.split(r"(?<=[.!?])\s+(?=[A-Z\"\(])", protected)
    return [p.replace("<DOT>", ".") for p in parts if p.strip()]
